# common/constants.py

MODE_REGISTER = 0
MODE_OWN = 1
MODE_NEED = 2
MODE_UPDATE = 3
MODE_EXIT = 4

DEFAULT_BUFFER_SIZE = 9216
DEFAULT_TRACKER_PORT = 12345
DEFAULT_TRACKER_HOST = "0.0.0.0"

DEFAULT_NODE_PORT = 20001
DEFAULT_BIND_HOST = "0.0.0.0"

DEFAULT_NODE_HEARTBEAT_INTERVAL = 20
DEFAULT_TRACKER_CHECK_INTERVAL = 22

DEFAULT_CHUNK_SIZE = 4096
DEFAULT_ACK_TIMEOUT = 1.0
DEFAULT_MAX_RETRIES = 20
